/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.ConnectDB.KetNoi;

/**
 *
 * @author ngomi
 */
public class TaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form TaiKhoan
     */
    public TaiKhoan() {
        initComponents();
        this.setLocationRelativeTo(null);   
        this.getDulieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        panel_TaiKhoan = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_TaiKhoan = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        taiKhoan_jPanel_nhanVien = new javax.swing.JPanel();
        taiKhoan_jTextField_taiKhoan_nv = new javax.swing.JTextField();
        taiKhoan_jTextField_diaChi_nv = new javax.swing.JTextField();
        taiKhoan_jTextField_hoTen_nv = new javax.swing.JTextField();
        taiKhoan_jTextField_soCMND_nv = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        taiKhoan_jTextField_soDienThoai_nv = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        taiKhoan_jTextField_ngaySinh_nv = new javax.swing.JTextField();
        taiKhoan_jComboBox_gioiTinh_nv = new javax.swing.JComboBox();
        taiKhoan_jPanel_Admin = new javax.swing.JPanel();
        taiKhoan_jTextField_ngaySinh_ad = new javax.swing.JTextField();
        taiKhoan_jTextField_diaChi_ad = new javax.swing.JTextField();
        taiKhoan_jTextField_soDienThoai_ad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        taiKhoan_jTextField_taiKhoan_ad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        taiKhoan_jTextField_hoTen_ad = new javax.swing.JTextField();
        taiKhoan_jButton_ThemTKAD = new javax.swing.JButton();
        taiKhoan_jButton_XoaTKAD = new javax.swing.JButton();
        taiKhoan_jButton_SuaTKAD = new javax.swing.JButton();
        taiKhoan_jButton_ResetAD = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        taiKhoan_jTextField_soCMND_ad = new javax.swing.JTextField();
        taiKhoan_jComboBox_gioiTinh_ad = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        taiKhoan_jPasswordField_matKhau_ad = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/group_52px_1.png"))); // NOI18N
        jLabel15.setText("Tài khoản");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel15)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        panel_TaiKhoan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_TaiKhoan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        table_TaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tài khoản", "Họ tên", "Ngày sinh", "Giới tinh", "Số điện thoại", "Địa chỉ", "Số CMND"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_TaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_TaiKhoan);

        panel_TaiKhoan.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 910, 180));

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        taiKhoan_jTextField_taiKhoan_nv.setPreferredSize(new java.awt.Dimension(100, 20));

        taiKhoan_jTextField_diaChi_nv.setPreferredSize(new java.awt.Dimension(100, 20));

        taiKhoan_jTextField_hoTen_nv.setPreferredSize(new java.awt.Dimension(100, 20));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setLabel("Xem thông tin nhân viên");
        jButton2.setPreferredSize(new java.awt.Dimension(150, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        taiKhoan_jTextField_soDienThoai_nv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taiKhoan_jTextField_soDienThoai_nvActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setLabel("Cập nhật thông tin");
        jButton1.setPreferredSize(new java.awt.Dimension(150, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Reset");
        jButton3.setPreferredSize(new java.awt.Dimension(70, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setText("Tài khoản");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setText("Số điện thoại");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel17.setText("Họ tên");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel18.setText("Địa chỉ");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setText("Ngày sinh");

        jLabel20.setText("Số CMND");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel21.setText("Giới tính");

        taiKhoan_jComboBox_gioiTinh_nv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));
        taiKhoan_jComboBox_gioiTinh_nv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taiKhoan_jComboBox_gioiTinh_nvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout taiKhoan_jPanel_nhanVienLayout = new javax.swing.GroupLayout(taiKhoan_jPanel_nhanVien);
        taiKhoan_jPanel_nhanVien.setLayout(taiKhoan_jPanel_nhanVienLayout);
        taiKhoan_jPanel_nhanVienLayout.setHorizontalGroup(
            taiKhoan_jPanel_nhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taiKhoan_jPanel_nhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taiKhoan_jPanel_nhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taiKhoan_jPanel_nhanVienLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(taiKhoan_jPanel_nhanVienLayout.createSequentialGroup()
                        .addGroup(taiKhoan_jPanel_nhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(taiKhoan_jPanel_nhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(taiKhoan_jTextField_taiKhoan_nv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(taiKhoan_jTextField_soDienThoai_nv))
                        .addGap(35, 35, 35)
                        .addGroup(taiKhoan_jPanel_nhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(taiKhoan_jPanel_nhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taiKhoan_jTextField_diaChi_nv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taiKhoan_jTextField_hoTen_nv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(taiKhoan_jPanel_nhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(taiKhoan_jPanel_nhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taiKhoan_jTextField_soCMND_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(taiKhoan_jPanel_nhanVienLayout.createSequentialGroup()
                                .addComponent(taiKhoan_jTextField_ngaySinh_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taiKhoan_jComboBox_gioiTinh_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 283, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        taiKhoan_jPanel_nhanVienLayout.setVerticalGroup(
            taiKhoan_jPanel_nhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taiKhoan_jPanel_nhanVienLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(taiKhoan_jPanel_nhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoan_jTextField_taiKhoan_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoan_jTextField_hoTen_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoan_jTextField_ngaySinh_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoan_jComboBox_gioiTinh_nv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(taiKhoan_jPanel_nhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoan_jTextField_diaChi_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoan_jTextField_soCMND_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoan_jTextField_soDienThoai_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(taiKhoan_jPanel_nhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Nhân viên", taiKhoan_jPanel_nhanVien);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("Số điện thoại");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("Địa chỉ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("Ngày sinh");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setText("Tài khoản");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setText("Họ tên");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setText("Giới tính");

        taiKhoan_jButton_ThemTKAD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        taiKhoan_jButton_ThemTKAD.setText("Thêm tài khoản nhân viên");
        taiKhoan_jButton_ThemTKAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taiKhoan_jButton_ThemTKADActionPerformed(evt);
            }
        });

        taiKhoan_jButton_XoaTKAD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        taiKhoan_jButton_XoaTKAD.setText("Xoá tài khoản nhân viên");
        taiKhoan_jButton_XoaTKAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taiKhoan_jButton_XoaTKADActionPerformed(evt);
            }
        });

        taiKhoan_jButton_SuaTKAD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        taiKhoan_jButton_SuaTKAD.setText("Sửa tài khoản nhân viên");

        taiKhoan_jButton_ResetAD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        taiKhoan_jButton_ResetAD.setText("Reset");

        jLabel13.setText("Số CMND");

        taiKhoan_jComboBox_gioiTinh_ad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));

        jLabel1.setText("Mật khẩu");

        taiKhoan_jPasswordField_matKhau_ad.setText("jPasswordField1");

        javax.swing.GroupLayout taiKhoan_jPanel_AdminLayout = new javax.swing.GroupLayout(taiKhoan_jPanel_Admin);
        taiKhoan_jPanel_Admin.setLayout(taiKhoan_jPanel_AdminLayout);
        taiKhoan_jPanel_AdminLayout.setHorizontalGroup(
            taiKhoan_jPanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taiKhoan_jPanel_AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taiKhoan_jPanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taiKhoan_jPanel_AdminLayout.createSequentialGroup()
                        .addComponent(taiKhoan_jButton_ThemTKAD)
                        .addGap(20, 20, 20)
                        .addComponent(taiKhoan_jButton_XoaTKAD)
                        .addGap(20, 20, 20)
                        .addComponent(taiKhoan_jButton_SuaTKAD)
                        .addGap(20, 20, 20)
                        .addComponent(taiKhoan_jButton_ResetAD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(taiKhoan_jPanel_AdminLayout.createSequentialGroup()
                        .addGroup(taiKhoan_jPanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1))
                        .addGap(22, 22, 22)
                        .addGroup(taiKhoan_jPanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(taiKhoan_jTextField_taiKhoan_ad, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(taiKhoan_jPasswordField_matKhau_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(taiKhoan_jPanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(taiKhoan_jPanel_AdminLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taiKhoan_jTextField_soDienThoai_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(taiKhoan_jPanel_AdminLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taiKhoan_jTextField_hoTen_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(taiKhoan_jPanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taiKhoan_jTextField_ngaySinh_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taiKhoan_jTextField_diaChi_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(taiKhoan_jPanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(taiKhoan_jPanel_AdminLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taiKhoan_jComboBox_gioiTinh_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(taiKhoan_jPanel_AdminLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taiKhoan_jTextField_soCMND_ad)))
                        .addGap(156, 156, 156))))
        );
        taiKhoan_jPanel_AdminLayout.setVerticalGroup(
            taiKhoan_jPanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taiKhoan_jPanel_AdminLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(taiKhoan_jPanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoan_jTextField_taiKhoan_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoan_jTextField_hoTen_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoan_jTextField_ngaySinh_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoan_jComboBox_gioiTinh_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(taiKhoan_jPanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoan_jTextField_diaChi_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoan_jTextField_soDienThoai_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(taiKhoan_jTextField_soCMND_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(taiKhoan_jPasswordField_matKhau_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(taiKhoan_jPanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taiKhoan_jButton_ThemTKAD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoan_jButton_XoaTKAD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoan_jButton_SuaTKAD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoan_jButton_ResetAD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Admin", taiKhoan_jPanel_Admin);

        panel_TaiKhoan.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 910, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        taiKhoan_jComboBox_gioiTinh_nv.setSelectedIndex(0);
        taiKhoan_jTextField_hoTen_nv.setText("");
        taiKhoan_jTextField_soDienThoai_nv.setText("");
        taiKhoan_jTextField_taiKhoan_nv.setText("");
        taiKhoan_jTextField_diaChi_nv.setText(""); 
        taiKhoan_jTextField_ngaySinh_nv.setText("");
        taiKhoan_jTextField_taiKhoan_nv.setText("");
        taiKhoan_jTextField_soCMND_nv.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed
    public void getDulieu()
    {
        KetNoi ketNoi = new KetNoi();
        ketNoi.Mo();
        String query = "SELECT * FROM NHANVIEN";
        System.out.println(query);
        ResultSet rs = ketNoi.LayDL(query);
// create a table model and set a Column Identifiers to this model 
        Object[] columns = {"Tài khoản","Họ và tên","Ngày sinh","Giới tính","Số điện thoại","Số CMND","Quê quán"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        table_TaiKhoan.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));        
        table_TaiKhoan.getTableHeader().setOpaque(false);
        table_TaiKhoan.getTableHeader().setBackground(new Color(32, 136, 203));
        table_TaiKhoan.getTableHeader().setForeground(new Color(255,255,255));
        table_TaiKhoan.setRowHeight(25);
// create an array of objects to set the row data
        try {
            while(rs.next())
            {
                Object rowData[] = new Object[7]; 
                rowData[0]=rs.getString(1);
                rowData[2]=rs.getString(2);
                rowData[3]=rs.getString(3);
                rowData[4]=rs.getString(4);
                rowData[5]=rs.getString(5);
                rowData[6]=rs.getString(6);
                rowData[7]=rs.getString(7);
                model.addRow(rowData);
                table_TaiKhoan.setModel(model);
                System.out.println("add du lieu vao bang thanh cong!");        
            }
        } catch (SQLException ex) {
            Logger.getLogger(TaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("add du lieu vao bang that bai!");
        }
        ketNoi.DongKetNoi();
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void taiKhoan_jButton_ThemTKADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taiKhoan_jButton_ThemTKADActionPerformed
        KetNoi ketNoi = new KetNoi();
        ketNoi.Mo();
        String taiKhoan = taiKhoan_jTextField_taiKhoan_ad.getText();
        String matKhau = taiKhoan_jPasswordField_matKhau_ad.getText();
        String hoTen = taiKhoan_jTextField_hoTen_ad.getText();
        String ngaySinh = taiKhoan_jTextField_ngaySinh_ad.getText();
        String gioiTinh = (String)taiKhoan_jComboBox_gioiTinh_ad.getSelectedItem();
        String soDienThoai = taiKhoan_jTextField_soDienThoai_ad.getText();
        String soCMND = taiKhoan_jTextField_soCMND_ad.getText();
        String diaChi =taiKhoan_jTextField_diaChi_ad.getText();
        if (gioiTinh.equals("Nam"))
            gioiTinh = "1";
        else
            gioiTinh = "0";
        String query = "INSERT INTO NHANVIEN VALUES('"
               +taiKhoan+"','"
               +matKhau+"','"
               +hoTen+"','"
               +ngaySinh+"',"
               +gioiTinh+",'"
               +soDienThoai+"','"
               +soCMND+"','"
               +diaChi+"',0)";
        System.out.println(query);
        if (ketNoi.CapNhat(query))
        {
            JOptionPane.showMessageDialog(rootPane,"Thêm tài khoản thành công!");
            this.getDulieu();
        }
        else 
            JOptionPane.showMessageDialog(rootPane,"Thêm tài khoản không thành công!");
        ketNoi.DongKetNoi();
    }//GEN-LAST:event_taiKhoan_jButton_ThemTKADActionPerformed

    private void taiKhoan_jButton_XoaTKADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taiKhoan_jButton_XoaTKADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taiKhoan_jButton_XoaTKADActionPerformed

    private void taiKhoan_jTextField_soDienThoai_nvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taiKhoan_jTextField_soDienThoai_nvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taiKhoan_jTextField_soDienThoai_nvActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void table_TaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_TaiKhoanMouseClicked
        int index = table_TaiKhoan.getSelectedRow();
        taiKhoan_jTextField_taiKhoan_nv.setText((String)table_TaiKhoan.getValueAt(index, 0));
        taiKhoan_jTextField_hoTen_nv.setText((String)table_TaiKhoan.getValueAt(index, 1));
        taiKhoan_jTextField_ngaySinh_nv.setText((String)table_TaiKhoan.getValueAt(index, 2));
        taiKhoan_jTextField_soDienThoai_nv.setText((String)table_TaiKhoan.getValueAt(index, 4));
        taiKhoan_jTextField_diaChi_nv.setText((String)table_TaiKhoan.getValueAt(index, 5));
        taiKhoan_jTextField_soCMND_nv.setText((String)table_TaiKhoan.getValueAt(index, 6));
        if (((String)table_TaiKhoan.getValueAt(index, 3)).equals("1"))
            taiKhoan_jComboBox_gioiTinh_nv.setSelectedIndex(0);
        else
            taiKhoan_jComboBox_gioiTinh_nv.setSelectedIndex(1);
    }//GEN-LAST:event_table_TaiKhoanMouseClicked

    private void taiKhoan_jComboBox_gioiTinh_nvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taiKhoan_jComboBox_gioiTinh_nvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taiKhoan_jComboBox_gioiTinh_nvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel panel_TaiKhoan;
    private javax.swing.JTable table_TaiKhoan;
    private javax.swing.JButton taiKhoan_jButton_ResetAD;
    private javax.swing.JButton taiKhoan_jButton_SuaTKAD;
    private javax.swing.JButton taiKhoan_jButton_ThemTKAD;
    private javax.swing.JButton taiKhoan_jButton_XoaTKAD;
    private javax.swing.JComboBox taiKhoan_jComboBox_gioiTinh_ad;
    private javax.swing.JComboBox taiKhoan_jComboBox_gioiTinh_nv;
    private javax.swing.JPanel taiKhoan_jPanel_Admin;
    private javax.swing.JPanel taiKhoan_jPanel_nhanVien;
    private javax.swing.JPasswordField taiKhoan_jPasswordField_matKhau_ad;
    private javax.swing.JTextField taiKhoan_jTextField_diaChi_ad;
    private javax.swing.JTextField taiKhoan_jTextField_diaChi_nv;
    private javax.swing.JTextField taiKhoan_jTextField_hoTen_ad;
    private javax.swing.JTextField taiKhoan_jTextField_hoTen_nv;
    private javax.swing.JTextField taiKhoan_jTextField_ngaySinh_ad;
    private javax.swing.JTextField taiKhoan_jTextField_ngaySinh_nv;
    private javax.swing.JTextField taiKhoan_jTextField_soCMND_ad;
    private javax.swing.JTextField taiKhoan_jTextField_soCMND_nv;
    private javax.swing.JTextField taiKhoan_jTextField_soDienThoai_ad;
    private javax.swing.JTextField taiKhoan_jTextField_soDienThoai_nv;
    private javax.swing.JTextField taiKhoan_jTextField_taiKhoan_ad;
    private javax.swing.JTextField taiKhoan_jTextField_taiKhoan_nv;
    // End of variables declaration//GEN-END:variables
}
