/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import main.ConnectDB.KetNoi;

/**
 *
 * @author ngomi
 */
public class ThongTinMuaBan extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinMuaBan
     */
    public ThongTinMuaBan() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    KetNoi ketNoi = new KetNoi();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_ThongTinMuaBan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        giaoDich_jButton_them = new javax.swing.JButton();
        giaoDich_jButton_sua = new javax.swing.JButton();
        giaoDich_jButton_timKiem = new javax.swing.JButton();
        giaoDich_jTextField_ngayGiaoDich = new javax.swing.JTextField();
        giaoDich_jTextField_diaChiKhachHang = new javax.swing.JTextField();
        giaoDich_jTextField_tenKhachHang = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        giaoDich_jTextField_maHopDong = new javax.swing.JTextField();
        giaoDich_jTextField_maKhachHang = new javax.swing.JTextField();
        giaoDich_jComboBox_maCanHo = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        giaoDich_jTextField_gia = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        giaoDich_jButton_xoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/group_52px_1.png"))); // NOI18N
        jLabel15.setText("Giao dịch");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel15)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_ThongTinMuaBan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        table_ThongTinMuaBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hợp đồng", "Mã khách hàng", "Tên khách hàng", "Địa chỉ khách hàng", "Mã căn hộ", "Giá", "Ngày giao dịch"
            }
        ));
        jScrollPane5.setViewportView(table_ThongTinMuaBan);

        jPanel5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 926, 170));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        giaoDich_jButton_them.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        giaoDich_jButton_them.setText("Thêm");
        giaoDich_jButton_them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                giaoDich_jButton_themMouseClicked(evt);
            }
        });
        jPanel2.add(giaoDich_jButton_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        giaoDich_jButton_sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        giaoDich_jButton_sua.setText("Sửa");
        giaoDich_jButton_sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                giaoDich_jButton_suaMouseClicked(evt);
            }
        });
        jPanel2.add(giaoDich_jButton_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        giaoDich_jButton_timKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        giaoDich_jButton_timKiem.setText("Reset");
        giaoDich_jButton_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giaoDich_jButton_timKiemActionPerformed(evt);
            }
        });
        jPanel2.add(giaoDich_jButton_timKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, -1, -1));
        jPanel2.add(giaoDich_jTextField_ngayGiaoDich, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 110, -1));
        jPanel2.add(giaoDich_jTextField_diaChiKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 160, -1));
        jPanel2.add(giaoDich_jTextField_tenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 110, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Tên khách hàng");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Địa chỉ khách hàng");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Ngày giao dịch");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));
        jPanel2.add(giaoDich_jTextField_maHopDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 110, -1));
        jPanel2.add(giaoDich_jTextField_maKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 110, -1));

        giaoDich_jComboBox_maCanHo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A100", "B101", "C203" }));
        giaoDich_jComboBox_maCanHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giaoDich_jComboBox_maCanHoActionPerformed(evt);
            }
        });
        jPanel2.add(giaoDich_jComboBox_maCanHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 110, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Mã hợp đồng");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Mã Khách hàng");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Mã căn hộ");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        giaoDich_jTextField_gia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giaoDich_jTextField_giaActionPerformed(evt);
            }
        });
        jPanel2.add(giaoDich_jTextField_gia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 110, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Giá");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        giaoDich_jButton_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        giaoDich_jButton_xoa.setText("Xoá");
        giaoDich_jButton_xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                giaoDich_jButton_xoaMouseClicked(evt);
            }
        });
        giaoDich_jButton_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giaoDich_jButton_xoaActionPerformed(evt);
            }
        });
        jPanel2.add(giaoDich_jButton_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 910, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void giaoDich_jButton_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giaoDich_jButton_timKiemActionPerformed
        // TODO add your handling code here:
        
        giaoDich_jTextField_maHopDong.setText("");       
        giaoDich_jTextField_gia.setText("");
        giaoDich_jTextField_ngayGiaoDich.setText("");
        giaoDich_jTextField_maKhachHang.setText("");
        giaoDich_jTextField_tenKhachHang.setText("");
        giaoDich_jTextField_diaChiKhachHang.setText("");
        
    }//GEN-LAST:event_giaoDich_jButton_timKiemActionPerformed

    private void giaoDich_jButton_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giaoDich_jButton_xoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giaoDich_jButton_xoaActionPerformed

    private void giaoDich_jComboBox_maCanHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giaoDich_jComboBox_maCanHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giaoDich_jComboBox_maCanHoActionPerformed

    private void giaoDich_jTextField_giaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giaoDich_jTextField_giaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giaoDich_jTextField_giaActionPerformed

    private void giaoDich_jButton_themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giaoDich_jButton_themMouseClicked
        // TODO add your handling code here:
        String maHopDong = giaoDich_jTextField_maHopDong.getText();
        String maCanHo = (String) giaoDich_jComboBox_maCanHo.getSelectedItem();
        String gia = giaoDich_jTextField_gia.getText();
        String ngayGiaoDich = giaoDich_jTextField_ngayGiaoDich.getText();
        String maKhachHang = giaoDich_jTextField_maKhachHang.getText();
        String tenKhachHang = giaoDich_jTextField_tenKhachHang.getText();
        String diaChi = giaoDich_jTextField_diaChiKhachHang.getText();
        
        String query = "INSERT INTO GIAODICH VALUES("+maHopDong+",'"+maKhachHang+"',"+tenKhachHang+",'"
                +diaChi+"','"+maCanHo+"',"+gia+"','"+ngayGiaoDich+")";
        ketNoi.CapNhat(query);
        
        //show
        String query1 = "SELECT * FROM GIAODICH ";
        ResultSet rs = ketNoi.LayDL(query1);
        DefaultTableModel tbl = new DefaultTableModel();
        try{
            while(rs.next()){
                Object rowData[] = new Object[7];
                rowData[0] = rs.getString(1);
                rowData[1] = rs.getString(2);
                rowData[2] = rs.getString(3);
                rowData[3] = rs.getString(4);
                rowData[4] = rs.getString(5);
                rowData[5] = rs.getString(6);
                rowData[6] = rs.getString(7);
                tbl.addRow(rowData);
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_giaoDich_jButton_themMouseClicked

    private void giaoDich_jButton_suaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giaoDich_jButton_suaMouseClicked
        // TODO add your handling code here:
        String maHopDong = giaoDich_jTextField_maHopDong.getText();
        String maCanHo = (String) giaoDich_jComboBox_maCanHo.getSelectedItem();
        String gia = giaoDich_jTextField_gia.getText();
        String ngayGiaoDich = giaoDich_jTextField_ngayGiaoDich.getText();
        String maKhachHang = giaoDich_jTextField_maKhachHang.getText();
        String tenKhachHang = giaoDich_jTextField_tenKhachHang.getText();
        String diaChi = giaoDich_jTextField_diaChiKhachHang.getText();
        
        int hangDuocChon = table_ThongTinMuaBan.getSelectedRow();
        String maTemp = table_ThongTinMuaBan.getValueAt(hangDuocChon, 0).toString();
        String query = "UPDATE GIAODICH SET maKhachHang="+maKhachHang+","
                + "tenKhachhang='"+tenKhachHang+"', diaChi='"+diaChi+"',maCanHo="+maCanHo+", gia="+gia+", ngayGiaoDich='"+ngayGiaoDich+"' where maHopDong="+maTemp;
        ketNoi.CapNhat(query);
        
        //show
        String query1 = "SELECT * FROM GIAODICH ";
        ResultSet rs = ketNoi.LayDL(query1);
        DefaultTableModel tbl = new DefaultTableModel();
        try{
            while(rs.next()){
                Object rowData[] = new Object[7];
                rowData[0] = rs.getString(1);
                rowData[1] = rs.getString(2);
                rowData[2] = rs.getString(3);
                rowData[3] = rs.getString(4);
                rowData[4] = rs.getString(5);
                rowData[5] = rs.getString(6);
                rowData[6] = rs.getString(7);
                tbl.addRow(rowData);
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_giaoDich_jButton_suaMouseClicked

    private void giaoDich_jButton_xoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giaoDich_jButton_xoaMouseClicked
        // TODO add your handling code here:
        String maHopDong = giaoDich_jTextField_maHopDong.getText();
        String maCanHo = (String) giaoDich_jComboBox_maCanHo.getSelectedItem();
        String gia = giaoDich_jTextField_gia.getText();
        String ngayGiaoDich = giaoDich_jTextField_ngayGiaoDich.getText();
        String maKhachHang = giaoDich_jTextField_maKhachHang.getText();
        String tenKhachHang = giaoDich_jTextField_tenKhachHang.getText();
        String diaChi = giaoDich_jTextField_diaChiKhachHang.getText();
        
        int hangDuocChon = table_ThongTinMuaBan.getSelectedRow();
        String maTemp = table_ThongTinMuaBan.getValueAt(hangDuocChon, 0).toString();
        
        String query = "DELETE from GIADICH where maHopDong="+maTemp;
        ketNoi.CapNhat(query);
        
        
        //show
        String query1 = "SELECT * FROM GIAODICH ";
        ResultSet rs = ketNoi.LayDL(query1);
        DefaultTableModel tbl = new DefaultTableModel();
        try{
            while(rs.next()){
                Object rowData[] = new Object[7];
                rowData[0] = rs.getString(1);
                rowData[1] = rs.getString(2);
                rowData[2] = rs.getString(3);
                rowData[3] = rs.getString(4);
                rowData[4] = rs.getString(5);
                rowData[5] = rs.getString(6);
                rowData[6] = rs.getString(7);
                tbl.addRow(rowData);
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_giaoDich_jButton_xoaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinMuaBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinMuaBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinMuaBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinMuaBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinMuaBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton giaoDich_jButton_sua;
    private javax.swing.JButton giaoDich_jButton_them;
    private javax.swing.JButton giaoDich_jButton_timKiem;
    private javax.swing.JButton giaoDich_jButton_xoa;
    private javax.swing.JComboBox<String> giaoDich_jComboBox_maCanHo;
    private javax.swing.JTextField giaoDich_jTextField_diaChiKhachHang;
    private javax.swing.JTextField giaoDich_jTextField_gia;
    private javax.swing.JTextField giaoDich_jTextField_maHopDong;
    private javax.swing.JTextField giaoDich_jTextField_maKhachHang;
    private javax.swing.JTextField giaoDich_jTextField_ngayGiaoDich;
    private javax.swing.JTextField giaoDich_jTextField_tenKhachHang;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable table_ThongTinMuaBan;
    // End of variables declaration//GEN-END:variables
}
