/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import main.ConnectDB.KetNoi;

/**
 *
 * @author ngomi
 */
public class ThongTinDanCu extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinDanCu
     */
    public ThongTinDanCu() {
        initComponents();
     //   this.setLocationRelativeTo(null);
        this.getDulieu();
    }
   KetNoi ketNoi = new KetNoi();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        panel_ThongTinDanCu = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        table_ThongTinDanCu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        khachHang_jTextField_soDienThoai = new javax.swing.JTextField();
        khachHang_jTextField_soCMND = new javax.swing.JTextField();
        khachHang_jTextField_queQuan = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        khachHang_jTextField_maKhachHang = new javax.swing.JTextField();
        khachHang_jTextField_tenKhachHang = new javax.swing.JTextField();
        khachHang_jTextField_ngaySinh = new javax.swing.JTextField();
        khachHang_jComboBox_gioiTinh = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        khachHang_jButton_reset = new javax.swing.JButton();
        khachHang_jButton_xoa = new javax.swing.JButton();
        khachHang_jButton_sua = new javax.swing.JButton();
        khachHang_jButton_them = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/group_52px_1.png"))); // NOI18N
        jLabel15.setText("Khách hàng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel15)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        panel_ThongTinDanCu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_ThongTinDanCu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Ngày sinh", "Giới tính", "Số điện thoại", "Số CMND", "Quê quán"
            }
        ));
        table_ThongTinDanCu.setInheritsPopupMenu(true);
        table_ThongTinDanCu.setPreferredSize(new java.awt.Dimension(775, 150));
        table_ThongTinDanCu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_ThongTinDanCuMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(table_ThongTinDanCu);

        panel_ThongTinDanCu.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 11, 943, 170));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(khachHang_jTextField_soDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 110, -1));

        khachHang_jTextField_soCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khachHang_jTextField_soCMNDActionPerformed(evt);
            }
        });
        jPanel2.add(khachHang_jTextField_soCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 110, -1));
        jPanel2.add(khachHang_jTextField_queQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 150, -1));

        jLabel33.setText("Quê quán");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        jLabel32.setText("Số CMND");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jLabel31.setText("Số điện thoại");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));
        jPanel2.add(khachHang_jTextField_maKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 110, -1));
        jPanel2.add(khachHang_jTextField_tenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 110, -1));
        jPanel2.add(khachHang_jTextField_ngaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 110, -1));

        khachHang_jComboBox_gioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));
        jPanel2.add(khachHang_jComboBox_gioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 90, -1));

        jLabel27.setText("Mã khách hàng");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel28.setText("Tên khách hàng");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jLabel29.setText("Ngày sinh");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jLabel30.setText("Giới tính");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        khachHang_jButton_reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        khachHang_jButton_reset.setText("Reset");
        khachHang_jButton_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khachHang_jButton_resetMouseClicked(evt);
            }
        });
        jPanel2.add(khachHang_jButton_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        khachHang_jButton_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        khachHang_jButton_xoa.setText("Xoá");
        khachHang_jButton_xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khachHang_jButton_xoaMouseClicked(evt);
            }
        });
        jPanel2.add(khachHang_jButton_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        khachHang_jButton_sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        khachHang_jButton_sua.setText("Sửa");
        khachHang_jButton_sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khachHang_jButton_suaMouseClicked(evt);
            }
        });
        jPanel2.add(khachHang_jButton_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        khachHang_jButton_them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        khachHang_jButton_them.setText("Thêm");
        khachHang_jButton_them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khachHang_jButton_themMouseClicked(evt);
            }
        });
        jPanel2.add(khachHang_jButton_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel1.setText("Tìm kiếm");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 110, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã khách hàng", "Tên khách hàng" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, -1, -1));

        panel_ThongTinDanCu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 920, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel_ThongTinDanCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_ThongTinDanCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void khachHang_jTextField_soCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khachHang_jTextField_soCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_khachHang_jTextField_soCMNDActionPerformed

    private void khachHang_jButton_themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachHang_jButton_themMouseClicked
        // TODO add your handling code here:
      
      ketNoi.Mo();
      String maKhacHang = khachHang_jTextField_maKhachHang.getText();
      String tenKhachHang = khachHang_jTextField_tenKhachHang.getText();
      String ngaySinh = khachHang_jTextField_ngaySinh.getText();
      String gioiTinh = (String)khachHang_jComboBox_gioiTinh.getSelectedItem();
      String soDienThoai = khachHang_jTextField_soDienThoai.getText();
      String soCMND = khachHang_jTextField_soCMND.getText();
      String queQuan =khachHang_jTextField_queQuan.getText();

       if (gioiTinh.equals("Nam"))
           gioiTinh = "1";
       else
           gioiTinh = "0";
      String query = "INSERT INTO KHACHHANG VALUES('"
              +maKhacHang+"','"
              +tenKhachHang+"','"
              +ngaySinh+"',"
              +gioiTinh+",'"
              +soDienThoai+"','"
              +soCMND+"','"
              +queQuan+"')";
    System.out.println(query);
    ketNoi.CapNhat(query);
    this.getDulieu();
    }//GEN-LAST:event_khachHang_jButton_themMouseClicked

    private void table_ThongTinDanCuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_ThongTinDanCuMouseClicked
        // TODO add your handling code here:
        int rowSelected = table_ThongTinDanCu.getSelectedRow();
        khachHang_jTextField_maKhachHang.setText(table_ThongTinDanCu.getValueAt(rowSelected, 0).toString());
        khachHang_jTextField_tenKhachHang.setText(table_ThongTinDanCu.getValueAt(rowSelected, 1).toString());
        khachHang_jTextField_ngaySinh.setText(table_ThongTinDanCu.getValueAt(rowSelected, 2).toString());
        khachHang_jTextField_soDienThoai.setText(table_ThongTinDanCu.getValueAt(rowSelected, 4).toString());
        khachHang_jTextField_soCMND.setText(table_ThongTinDanCu.getValueAt(rowSelected, 5).toString());
        khachHang_jTextField_queQuan.setText(table_ThongTinDanCu.getValueAt(rowSelected, 6).toString());
    }//GEN-LAST:event_table_ThongTinDanCuMouseClicked

    private void khachHang_jButton_suaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachHang_jButton_suaMouseClicked
        // TODO add your handling code here:
        String maKhachHang = khachHang_jTextField_maKhachHang.getText();
        String tenKhachHang = khachHang_jTextField_tenKhachHang.getText();
        String ngaySinh = khachHang_jTextField_ngaySinh.getText();
        String soDienThoai = khachHang_jTextField_soDienThoai.getText();
        String soCMND = khachHang_jTextField_soCMND.getText();
        String queQuan = khachHang_jTextField_queQuan.getText();
        int hangDuocChon = table_ThongTinDanCu.getSelectedRow();
        String maKHTemp = table_ThongTinDanCu.getValueAt(hangDuocChon, 0).toString();
        String query = "UPDATE KHACHHANG SET tenKhachHang='"+tenKhachHang+"', ngaySinh='"
                +ngaySinh+"', soDienThoai='"+soDienThoai+"', soCMND="+soCMND+", queQuan='"+queQuan+"' "
                + "where maKhachHang="+maKHTemp;
        ketNoi.Mo();
        ketNoi.CapNhat(query);
        
        //show
        this.getDulieu();       
        
        
    }//GEN-LAST:event_khachHang_jButton_suaMouseClicked

    private void khachHang_jButton_xoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachHang_jButton_xoaMouseClicked
        // TODO add your handling code here:
        String maKhachHang = khachHang_jTextField_maKhachHang.getText();
        String tenKhachHang = khachHang_jTextField_tenKhachHang.getText();
        String ngaySinh = khachHang_jTextField_ngaySinh.getText();
        String soDienThoai = khachHang_jTextField_soDienThoai.getText();
        String soCMND = khachHang_jTextField_soCMND.getText();
        String queQuan = khachHang_jTextField_queQuan.getText();
        int hangDuocChon = table_ThongTinDanCu.getSelectedRow();
        String maKHTemp = table_ThongTinDanCu.getValueAt(hangDuocChon, 0).toString();
        String query = "DELETE FROM KHACHHANG WHERE maKhachHang="+maKHTemp;
        ketNoi.Mo();
        ketNoi.CapNhat(query);
        
        this.getDulieu();
    }//GEN-LAST:event_khachHang_jButton_xoaMouseClicked

    private void khachHang_jButton_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachHang_jButton_resetMouseClicked
        // TODO add your handling code here:
        khachHang_jTextField_maKhachHang.setText("");
        khachHang_jTextField_tenKhachHang.setText("");
        khachHang_jTextField_ngaySinh.setText("");
        khachHang_jTextField_soDienThoai.setText("");
        khachHang_jTextField_soCMND.setText("");
        khachHang_jTextField_queQuan.setText("");
    }//GEN-LAST:event_khachHang_jButton_resetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinDanCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinDanCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinDanCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinDanCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinDanCu().setVisible(true);
            }
        });
    }
    public void getDulieu()
    {
        KetNoi ketNoi = new KetNoi();
        ketNoi.Mo();
        String query = "SELECT * FROM KHACHHANG;";
        System.out.println(query);
        ResultSet rs = ketNoi.LayDL(query);
// create a table model and set a Column Identifiers to this model 
        Object[] columns = {"Mã khách hàng","Tên khách hàng","Ngày sinh","Giới tính","Số điện thoại","Số CMND","Quê quán"};
        Object[] row = new Object[100];
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        table_ThongTinDanCu.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));        
        table_ThongTinDanCu.getTableHeader().setOpaque(false);
        table_ThongTinDanCu.getTableHeader().setBackground(new Color(32, 136, 203));
        table_ThongTinDanCu.getTableHeader().setForeground(new Color(255,255,255));
        table_ThongTinDanCu.setRowHeight(25);
// create an array of objects to set the row data
        try {
            while(rs.next())
            {
                Object rowData[] = new Object[7]; 
                rowData[0]=rs.getString(1);
                rowData[1]=rs.getString(2);
                rowData[2]=rs.getString(3);
                rowData[3]=rs.getString(4);
                rowData[4]=rs.getString(5);
                rowData[5]=rs.getString(6);
                rowData[6]=rs.getString(7);
                model.addRow(rowData);
                table_ThongTinDanCu.setModel(model);
                System.out.println("add du lieu vao bang thanh cong!");        
            }
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinDanCu.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("add du lieu vao bang that bai!");
        }
        ketNoi.DongKetNoi();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton khachHang_jButton_reset;
    private javax.swing.JButton khachHang_jButton_sua;
    private javax.swing.JButton khachHang_jButton_them;
    private javax.swing.JButton khachHang_jButton_xoa;
    private javax.swing.JComboBox<String> khachHang_jComboBox_gioiTinh;
    private javax.swing.JTextField khachHang_jTextField_maKhachHang;
    private javax.swing.JTextField khachHang_jTextField_ngaySinh;
    private javax.swing.JTextField khachHang_jTextField_queQuan;
    private javax.swing.JTextField khachHang_jTextField_soCMND;
    private javax.swing.JTextField khachHang_jTextField_soDienThoai;
    private javax.swing.JTextField khachHang_jTextField_tenKhachHang;
    private javax.swing.JPanel panel_ThongTinDanCu;
    private javax.swing.JTable table_ThongTinDanCu;
    // End of variables declaration//GEN-END:variables
}
