/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.ConnectDB.KetNoi;

/**
 *
 * @author ngomi
 */
public class ThongTinDanCu extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinDanCu
     */
    public ThongTinDanCu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getDulieu();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        panel_ThongTinDanCu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        khachHang_jTextField_soDienThoai = new javax.swing.JTextField();
        khachHang_jTextField_soCMND = new javax.swing.JTextField();
        khachHang_jTextField_queQuan = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        khachHang_jTextField_maKhachHang = new javax.swing.JTextField();
        khachHang_jTextField_tenKhachHang = new javax.swing.JTextField();
        khachHang_jTextField_ngaySinh = new javax.swing.JTextField();
        khachHang_jComboBox_gioiTinh = new javax.swing.JComboBox<String>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        khachHang_jButton_reset = new javax.swing.JButton();
        khachHang_jButton_xoa = new javax.swing.JButton();
        khachHang_jButton_sua = new javax.swing.JButton();
        khachHang_jButton_them = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_ThongTinDanCu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/group_52px_1.png"))); // NOI18N
        jLabel15.setText("Khách hàng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel15)
                .addContainerGap(651, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel15)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        panel_ThongTinDanCu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        khachHang_jTextField_soCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khachHang_jTextField_soCMNDActionPerformed(evt);
            }
        });

        jLabel33.setText("Quê quán");

        jLabel32.setText("Số CMND");

        jLabel31.setText("Số điện thoại");

        khachHang_jComboBox_gioiTinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ", "Khác" }));

        jLabel27.setText("Mã khách hàng");

        jLabel28.setText("Tên khách hàng");

        jLabel29.setText("Ngày sinh");

        jLabel30.setText("Giới tính");

        khachHang_jButton_reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        khachHang_jButton_reset.setText("Reset");
        khachHang_jButton_reset.setPreferredSize(new java.awt.Dimension(100, 30));
        khachHang_jButton_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khachHang_jButton_resetMouseClicked(evt);
            }
        });
        khachHang_jButton_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khachHang_jButton_resetActionPerformed(evt);
            }
        });

        khachHang_jButton_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        khachHang_jButton_xoa.setText("Xoá");
        khachHang_jButton_xoa.setPreferredSize(new java.awt.Dimension(100, 30));
        khachHang_jButton_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khachHang_jButton_xoaActionPerformed(evt);
            }
        });

        khachHang_jButton_sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        khachHang_jButton_sua.setText("Sửa");
        khachHang_jButton_sua.setPreferredSize(new java.awt.Dimension(100, 30));
        khachHang_jButton_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khachHang_jButton_suaActionPerformed(evt);
            }
        });

        khachHang_jButton_them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        khachHang_jButton_them.setText("Thêm");
        khachHang_jButton_them.setPreferredSize(new java.awt.Dimension(100, 30));
        khachHang_jButton_them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khachHang_jButton_themMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Tìm kiếm");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(khachHang_jTextField_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(khachHang_jTextField_tenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(khachHang_jTextField_maKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel33))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(khachHang_jTextField_queQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(khachHang_jTextField_soCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(khachHang_jTextField_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(khachHang_jComboBox_gioiTinh, 0, 110, Short.MAX_VALUE)
                                .addGap(281, 281, 281))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(khachHang_jButton_them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(khachHang_jButton_sua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(khachHang_jButton_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(khachHang_jButton_reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(khachHang_jTextField_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(khachHang_jTextField_soCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(khachHang_jTextField_queQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(khachHang_jTextField_maKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(khachHang_jTextField_tenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(khachHang_jTextField_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(khachHang_jComboBox_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(khachHang_jButton_them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(khachHang_jButton_sua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(khachHang_jButton_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(khachHang_jButton_reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panel_ThongTinDanCu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 910, 210));

        table_ThongTinDanCu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_ThongTinDanCu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_ThongTinDanCuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_ThongTinDanCu);

        panel_ThongTinDanCu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_ThongTinDanCu, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_ThongTinDanCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void khachHang_jTextField_soCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khachHang_jTextField_soCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_khachHang_jTextField_soCMNDActionPerformed

    private void khachHang_jButton_themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachHang_jButton_themMouseClicked
        // TODO add your handling code here:
        KetNoi ketNoi = new KetNoi();
        ketNoi.Mo();
        String maKhacHang = khachHang_jTextField_maKhachHang.getText();
        String tenKhachHang = khachHang_jTextField_tenKhachHang.getText();
        String ngaySinh = khachHang_jTextField_ngaySinh.getText();
        String gioiTinh = (String)khachHang_jComboBox_gioiTinh.getSelectedItem();
        String soDienThoai = khachHang_jTextField_soDienThoai.getText();
        String soCMND = khachHang_jTextField_soCMND.getText();
        String queQuan =khachHang_jTextField_queQuan.getText();

        if (gioiTinh.equals("Nam"))
            gioiTinh = "1";
        else
            gioiTinh = "0";
        String query = "INSERT INTO KHACHHANG VALUES('"
               +maKhacHang+"','"
               +tenKhachHang+"','"
               +ngaySinh+"',"
               +gioiTinh+",'"
               +soDienThoai+"','"
               +soCMND+"','"
               +queQuan+"')";
        System.out.println(query);
        if (ketNoi.CapNhat(query))
        {
            JOptionPane.showMessageDialog(rootPane, "Dữ liệu được thêm thành công!");
            this.getDulieu();
        }
        else 
            JOptionPane.showMessageDialog(rootPane, "Dữ liệu thêm không thành công!");
        ketNoi.DongKetNoi();
    }//GEN-LAST:event_khachHang_jButton_themMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.getDulieu();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void khachHang_jButton_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachHang_jButton_resetMouseClicked

    }//GEN-LAST:event_khachHang_jButton_resetMouseClicked

    private void khachHang_jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khachHang_jButton_resetActionPerformed
    //Reset
        khachHang_jTextField_maKhachHang.setText("");
        khachHang_jTextField_tenKhachHang.setText("");
        khachHang_jTextField_ngaySinh.setText("");
        khachHang_jTextField_queQuan.setText("");
        khachHang_jTextField_soCMND.setText("");
        khachHang_jTextField_soDienThoai.setText("");
        this.getDulieu();
    }//GEN-LAST:event_khachHang_jButton_resetActionPerformed

    private void table_ThongTinDanCuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_ThongTinDanCuMouseClicked
        // TODO add your handling code here:
        int index = table_ThongTinDanCu.getSelectedRow();
        khachHang_jTextField_maKhachHang.setText((String)table_ThongTinDanCu.getValueAt(index, 0));
        khachHang_jTextField_tenKhachHang.setText((String)table_ThongTinDanCu.getValueAt(index, 1));
        khachHang_jTextField_ngaySinh.setText((String)table_ThongTinDanCu.getValueAt(index, 2));
        khachHang_jTextField_queQuan.setText((String)table_ThongTinDanCu.getValueAt(index, 6));
        khachHang_jTextField_soCMND.setText((String)table_ThongTinDanCu.getValueAt(index, 5));
        khachHang_jTextField_soDienThoai.setText((String)table_ThongTinDanCu.getValueAt(index, 4));
        if (((String)table_ThongTinDanCu.getValueAt(index, 3)).equals("1"))
            khachHang_jComboBox_gioiTinh.setSelectedIndex(0);
        else
            khachHang_jComboBox_gioiTinh.setSelectedIndex(1);
    }//GEN-LAST:event_table_ThongTinDanCuMouseClicked

    private void khachHang_jButton_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khachHang_jButton_xoaActionPerformed
// Xoá thông tin dân cư 
        String maKhachHang = khachHang_jTextField_maKhachHang.getText();
        if (maKhachHang == null)
        {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập mã khách hàng hoặc chọn từ bảng thông tin!");
        }
        else
        {
            KetNoi ketNoi = new KetNoi();
            ketNoi.Mo();
            String query ="DELETE FROM KHACHHANG WHERE MAKHACHHANG = '"+maKhachHang+"'";
            System.out.println(query);
            if (ketNoi.CapNhat(query))
            {
            JOptionPane.showMessageDialog(rootPane, "Dữ liệu đã được xoá!");
            this.getDulieu();
            }
            else 
            JOptionPane.showMessageDialog(rootPane, "Dữ liệu xoá không thành công!");
            ketNoi.DongKetNoi();
        }
    }//GEN-LAST:event_khachHang_jButton_xoaActionPerformed

    private void khachHang_jButton_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khachHang_jButton_suaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_khachHang_jButton_suaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinDanCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinDanCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinDanCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinDanCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinDanCu().setVisible(true);
            }
        });
    }
    public void getDulieu()
    {
        KetNoi ketNoi = new KetNoi();
        ketNoi.Mo();
        String query = "SELECT * FROM KHACHHANG;";
        System.out.println(query);
        ResultSet rs = ketNoi.LayDL(query);
// create a table model and set a Column Identifiers to this model 
        Object[] columns = {"Mã khách hàng","Tên khách hàng","Ngày sinh","Giới tính","Số điện thoại","Số CMND","Quê quán"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        table_ThongTinDanCu.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));        
        table_ThongTinDanCu.getTableHeader().setOpaque(false);
        table_ThongTinDanCu.getTableHeader().setBackground(new Color(32, 136, 203));
        table_ThongTinDanCu.getTableHeader().setForeground(new Color(255,255,255));
        table_ThongTinDanCu.setRowHeight(25);
// create an array of objects to set the row data
        try {
            while(rs.next())
            {
                Object rowData[] = new Object[7]; 
                rowData[0]=rs.getString(1);
                rowData[1]=rs.getString(2);
                rowData[2]=rs.getString(3);
                rowData[3]=rs.getString(4);
                rowData[4]=rs.getString(5);
                rowData[5]=rs.getString(6);
                rowData[6]=rs.getString(7);
                model.addRow(rowData);
                table_ThongTinDanCu.setModel(model);
                System.out.println("add du lieu vao bang thanh cong!");        
            }
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinDanCu.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("add du lieu vao bang that bai!");
        }
        ketNoi.DongKetNoi();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton khachHang_jButton_reset;
    private javax.swing.JButton khachHang_jButton_sua;
    private javax.swing.JButton khachHang_jButton_them;
    private javax.swing.JButton khachHang_jButton_xoa;
    private javax.swing.JComboBox<String> khachHang_jComboBox_gioiTinh;
    private javax.swing.JTextField khachHang_jTextField_maKhachHang;
    private javax.swing.JTextField khachHang_jTextField_ngaySinh;
    private javax.swing.JTextField khachHang_jTextField_queQuan;
    private javax.swing.JTextField khachHang_jTextField_soCMND;
    private javax.swing.JTextField khachHang_jTextField_soDienThoai;
    private javax.swing.JTextField khachHang_jTextField_tenKhachHang;
    private javax.swing.JPanel panel_ThongTinDanCu;
    private javax.swing.JTable table_ThongTinDanCu;
    // End of variables declaration//GEN-END:variables
}
